#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

PROBE_DIR="${PROBE_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/cloud-session-probe.XXXXXX")}"
PORT="${CLOUD_PROBE_PORT:-18082}"
CONFDIR="${ANTIGRAVITY_MITM_CONFDIR:-$HOME/.mitmproxy}"
TRUST_MODE="${TRUST_MODE:-extra}"   # extra = NODE_EXTRA_CA_CERTS (adds a root); bundle = SSL_CERT_FILE (replaces the pool)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDON="$SCRIPT_DIR/mitm_cloud_session_probe.py"
LABEL_FILE="$PROBE_DIR/label"
OUT="$PROBE_DIR/probe.jsonl"
SUMMARY="$PROBE_DIR/SUMMARY.txt"
WORKSPACE="$PROBE_DIR/workspace"
BUNDLE="$PROBE_DIR/ca-bundle.pem"
ENV_FILE="$PROBE_DIR/.env-unused"   # the wizard never persists values
MITM_PID=""
CLOUD_SESSION_ID=""

cleanup() {
  if [[ -n "$MITM_PID" ]] && kill -0 "$MITM_PID" 2>/dev/null; then
    kill "$MITM_PID" 2>/dev/null || true
    wait "$MITM_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# claude_through_mitm ARGS...: process-scoped proxy + trust, no keychain change.
claude_through_mitm() {
  local trust=(NODE_EXTRA_CA_CERTS="$CONFDIR/mitmproxy-ca-cert.pem")
  [[ "$TRUST_MODE" == "bundle" ]] && trust=(SSL_CERT_FILE="$BUNDLE")
  ( cd "$WORKSPACE" && env \
      HTTPS_PROXY="http://127.0.0.1:$PORT" https_proxy="http://127.0.0.1:$PORT" \
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 \
      "${trust[@]}" claude "$@" )
}

banner "Claude Code cloud-session API probe (open question 1, probe C)"

# ── 1. Briefing and preflight ─────────────────────────────────────────────
stage "Read this, then confirm"
warn "This run creates a REAL cloud session on your Claude account."
say "What happens:"
step "claude --cloud uploads the working directory it is started in. The wizard uses a"
step "brand-new throwaway folder holding one dummy file. Nothing of yours is uploaded."
step "Your login token flows through a local intercepting proxy, but ONLY for hosts on"
step "anthropic.com, claude.ai and claude.com. Other hosts are tunnelled untouched."
step "The addon writes route shapes only: masked paths, key names, types, status codes."
step "It is built never to write tokens, prompts, file contents, repo names or raw ids."
say ""
say "Afterwards you archive the session at claude.ai/code (the wizard reminds you)."
confirm "Go ahead and create one throwaway cloud session?" || { say "Stopped. Nothing was created."; exit 0; }
command -v claude   >/dev/null 2>&1 || { warn "claude not found in PATH"; exit 1; }
command -v mitmdump >/dev/null 2>&1 || { warn "mitmdump missing: brew install mitmproxy"; exit 1; }
command -v python3  >/dev/null 2>&1 || { warn "python3 missing"; exit 1; }
[[ -f "$ADDON" ]]   || { warn "addon not found: $ADDON"; exit 1; }
say "claude:   $(claude --version 2>&1 | head -n1)"
if claude --help 2>&1 | grep -q -- '--cloud'; then
  say "flag:     --cloud is available in this build"
else
  warn "this claude does not list --cloud. Older builds used --remote; edit the run stages."
  exit 1
fi
say "workdir:  $PROBE_DIR"
pause "Continue?"

# ── 2. Throwaway workspace ────────────────────────────────────────────────
stage "Create the throwaway workspace"
mkdir -p "$WORKSPACE"
(
  cd "$WORKSPACE"
  git init -q
  printf 'cloud session probe, safe to delete\n' > README.txt
  git add README.txt
  git -c user.name=probe -c user.email=probe@example.invalid -c commit.gpgsign=false -c core.hooksPath=/dev/null commit -q -m "probe"
)
say "created $WORKSPACE (1 file, local git repo, no remote)"
note "If --cloud refuses a repo with no remote, the error will say so; paste it back instead of working around it."
pause "Continue?"

# ── 3. Start the intercepting proxy ───────────────────────────────────────
stage "Start mitmdump (Anthropic-owned hosts only)"
if [[ ! -f "$CONFDIR/mitmproxy-ca-cert.pem" ]]; then
  step "generating the mitmproxy CA (mitmdump runs ~3s)"
  mitmdump --listen-host 127.0.0.1 --listen-port "$PORT" --set "confdir=$CONFDIR" >/dev/null 2>&1 &
  MITM_PID=$!; sleep 3; cleanup; MITM_PID=""
fi
[[ -f "$CONFDIR/mitmproxy-ca-cert.pem" ]] || { warn "CA still missing in $CONFDIR"; exit 1; }
if [[ "$TRUST_MODE" == "bundle" ]]; then
  SYS_ROOTS="${SYSTEM_CA_FILE:-/etc/ssl/cert.pem}"
  [[ -f "$SYS_ROOTS" ]] || { warn "no system roots at $SYS_ROOTS; set SYSTEM_CA_FILE"; exit 1; }
  cat "$SYS_ROOTS" "$CONFDIR/mitmproxy-ca-cert.pem" > "$BUNDLE"
fi
: > "$OUT"; echo "startup" > "$LABEL_FILE"
# mitmproxy 12 matches allow_hosts against "host:port": tolerate :443.
PROBE_OUT="$OUT" PROBE_LABEL_FILE="$LABEL_FILE" mitmdump \
  --listen-host 127.0.0.1 --listen-port "$PORT" -s "$ADDON" \
  --set "allow_hosts=^([a-z0-9-]+\\.)*(anthropic\\.com|claude\\.ai|claude\\.com)(:443)?\$" \
  --set "confdir=$CONFDIR" > "$PROBE_DIR/mitmdump.log" 2>&1 &
MITM_PID=$!
for _ in $(seq 1 100); do nc -z 127.0.0.1 "$PORT" >/dev/null 2>&1 && break; sleep 0.1; done
nc -z 127.0.0.1 "$PORT" >/dev/null 2>&1 || { warn "mitmdump did not start; see $PROBE_DIR/mitmdump.log"; exit 1; }
say "✓ mitmdump on 127.0.0.1:$PORT (pid $MITM_PID), trust mode: $TRUST_MODE"
pause "Ready to create the session?"

# ── 4. Create the cloud session ───────────────────────────────────────────
stage "Create the cloud session"
echo "cloud-create" > "$LABEL_FILE"
say "claude starts interactively, in the throwaway folder, through the proxy."
step "Wait for it to say the session was created and the reply arrived."
step "Note the session id or the claude.ai/code URL it shows."
step "Then exit claude (/exit) and come back here."
pause "Press Enter to launch claude"
claude_through_mitm --cloud "Reply with exactly CLOUD_PROBE_OK. Do not modify any files." || warn "claude exited non-zero"
say "records so far: $(wc -l < "$OUT" | tr -d ' ')"
if [[ "$(wc -l < "$OUT" | tr -d ' ')" -eq 0 ]]; then
  warn "nothing was intercepted. Likely TLS trust: re-run with TRUST_MODE=bundle."
fi
say "Paste the session id (or the claude.ai/code URL). It stays in memory only."
ask CLOUD_SESSION_ID "Session id or URL (Enter to skip stage 5):"

# ── 5. Message and re-attach ──────────────────────────────────────────────
stage "Message and re-attach the session"
if [[ -z "$CLOUD_SESSION_ID" ]]; then
  say "No id given: skipping."
else
  echo "cloud-message-headless" > "$LABEL_FILE"
  step "headless message to the existing session …"
  claude_through_mitm -p "Reply with exactly CLOUD_PROBE_TWO" --cloud "$CLOUD_SESSION_ID" </dev/null || warn "headless message exited non-zero"
  echo "cloud-reattach" > "$LABEL_FILE"
  step "Next: interactive re-attach. Let it load, then exit with /exit."
  pause "Press Enter to launch"
  claude_through_mitm --cloud "$CLOUD_SESSION_ID" || warn "re-attach exited non-zero"
fi

# ── 6. Summarize and clean up ─────────────────────────────────────────────
stage "Summary and cleanup"
cleanup; MITM_PID=""
python3 - "$OUT" > "$SUMMARY" <<'PY'
import json, sys, collections
rows = [json.loads(l) for l in open(sys.argv[1]) if l.strip()]
http = [r for r in rows if r["kind"] == "http"]
print(f"records: {len(rows)}  http: {len(http)}")
conn = collections.Counter((r["host"], r["port"]) for r in rows if r["kind"] == "connect")
print("\nCONNECT hosts (all, including tunnelled):")
for (h, p), n in sorted(conn.items()):
    print(f"  {h}:{p}  x{n}")
ws = [r for r in rows if r["kind"] == "websocket"]
for r in ws:
    print(f"\nWEBSOCKET {r['host']} {r['path']}")
groups = collections.OrderedDict()
for r in http:
    groups.setdefault((r["method"], r["host"], r["path"]), []).append(r)
for (m, h, p), rs in groups.items():
    stat = collections.Counter((r["label"], r.get("status")) for r in rs)
    print(f"\n{m} {h}{p}")
    print("  seen:", ", ".join(f"{l}:{s}x{n}" for (l, s), n in sorted(stat.items(), key=str)))
    first = rs[0]
    if first.get("query_names"): print("  query:", first["query_names"])
    print("  req headers:", first["request_headers"]["names"])
    if first.get("request_body"): print("  req body:", json.dumps(first["request_body"])[:600])
    if first.get("response_body"): print("  res body:", json.dumps(first["response_body"])[:600])
for r in rows:
    if r["kind"] == "error":
        print(f"\nERROR {r.get('method')} {r['host']}{r['path']}: {r['error']}")
PY
say "Now archive the probe session: open https://claude.ai/code, find it (title mentions"
say "CLOUD_PROBE_OK), and archive or delete it."
open_url "https://claude.ai/code"
note "$SUMMARY is meant to hold only masked paths, key names, types and status codes. Skim it before pasting."
pause "Show the summary?"
printf '\n'; sed 's/^/  /' "$SUMMARY"; printf '\n'
say "Paste the summary above back to Claude. Files: $PROBE_DIR (probe.jsonl is shape-only)."
pause "Copied the summary? Press Enter to finish (the screen clears)."
# ──────────────────────────────────────────────────────────────────────────

finish
