#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

PROBE_DIR="${PROBE_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/agy-session-probe.XXXXXX")}"
PORT="${ANTIGRAVITY_MITM_PORT:-18081}"
CONFDIR="${ANTIGRAVITY_MITM_CONFDIR:-$HOME/.mitmproxy}"
AGY_BIN="${AGY_BIN:-$(command -v agy || echo "$HOME/.local/bin/agy")}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDON="$SCRIPT_DIR/mitm_agy_session_probe.py"
LABEL_FILE="$PROBE_DIR/label"
OUT="$PROBE_DIR/probe.jsonl"
SUMMARY="$PROBE_DIR/SUMMARY.txt"
BUNDLE="$PROBE_DIR/ca-bundle.pem"
MITM_PID=""

cleanup() {
  if [[ -n "$MITM_PID" ]] && kill -0 "$MITM_PID" 2>/dev/null; then
    kill "$MITM_PID" 2>/dev/null || true
    wait "$MITM_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# Runs agy through the local mitm with process-scoped trust only (no keychain).
agy_through_mitm() {
  env HTTPS_PROXY="http://127.0.0.1:$PORT" HTTP_PROXY="http://127.0.0.1:$PORT" \
    SSL_CERT_FILE="$BUNDLE" "$AGY_BIN" "$@"
}

banner "agy sessionId probe (open question 6)"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight"
say "Checks the tools and where results will land. Nothing is sent anywhere."
[[ -x "$AGY_BIN" ]] || { warn "agy not found at $AGY_BIN; set AGY_BIN=/path/to/agy and re-run"; exit 1; }
command -v mitmdump >/dev/null 2>&1 || { warn "mitmdump missing: brew install mitmproxy"; exit 1; }
command -v python3  >/dev/null 2>&1 || { warn "python3 missing"; exit 1; }
[[ -f "$ADDON" ]]   || { warn "addon not found: $ADDON"; exit 1; }
say "agy:      $AGY_BIN"
say "version:  $("$AGY_BIN" --version 2>&1 | head -n1)"
say "workdir:  $PROBE_DIR"
if [[ ! -f "$CONFDIR/mitmproxy-ca-cert.pem" ]]; then
  step "mitmproxy CA not generated yet. Creating it (mitmdump runs for ~3s, then stops)."
  mitmdump --listen-host 127.0.0.1 --listen-port "$PORT" --set "confdir=$CONFDIR" >/dev/null 2>&1 &
  MITM_PID=$!
  sleep 3
  cleanup; MITM_PID=""
fi
[[ -f "$CONFDIR/mitmproxy-ca-cert.pem" ]] || { warn "CA still missing in $CONFDIR"; exit 1; }
SYS_ROOTS="${SYSTEM_CA_FILE:-/etc/ssl/cert.pem}"
[[ -f "$SYS_ROOTS" ]] || { warn "no system roots at $SYS_ROOTS; set SYSTEM_CA_FILE=<bundle>"; exit 1; }
# SSL_CERT_FILE REPLACES the root pool on darwin, so the bundle is system roots + mitm CA.
cat "$SYS_ROOTS" "$CONFDIR/mitmproxy-ca-cert.pem" > "$BUNDLE"
say "trust:    process-scoped via SSL_CERT_FILE (no keychain change)"
pause "Looks right?"

# ── 2. Binary strings scan (probe A) ──────────────────────────────────────
stage "Scan the agy binary for session fields"
say "Static hints only: field names, not runtime behavior."
strings -n 6 "$AGY_BIN" \
  | grep -oiE '.{0,40}(sessionId|session_id|conversationId|conversation_id|trajectoryId|trajectory_id).{0,40}' \
  | sort -u > "$PROBE_DIR/strings-hits.txt" || true
say "unique hits: $(wc -l < "$PROBE_DIR/strings-hits.txt" | tr -d ' ')  (saved: $PROBE_DIR/strings-hits.txt)"
note "first 25:"
head -n 25 "$PROBE_DIR/strings-hits.txt" | sed 's/^/    /'
pause "Continue to the capture?"

# ── 3. Start the intercepting proxy ───────────────────────────────────────
stage "Start mitmdump (scoped to Cloud Code hosts)"
say "Only session/conversation/trajectory fields are recorded, as 8-char hashes."
: > "$OUT"; echo "startup" > "$LABEL_FILE"
# mitmproxy 12 matches allow_hosts against "host:port": the regex must tolerate :443.
PROBE_OUT="$OUT" PROBE_LABEL_FILE="$LABEL_FILE" mitmdump \
  --listen-host 127.0.0.1 --listen-port "$PORT" -s "$ADDON" \
  --set "allow_hosts=^(cloudcode|daily-cloudcode)-pa\\.googleapis\\.com(:443)?\$" \
  --set "confdir=$CONFDIR" > "$PROBE_DIR/mitmdump.log" 2>&1 &
MITM_PID=$!
for _ in $(seq 1 100); do nc -z 127.0.0.1 "$PORT" >/dev/null 2>&1 && break; sleep 0.1; done
nc -z 127.0.0.1 "$PORT" >/dev/null 2>&1 || { warn "mitmdump did not start; see $PROBE_DIR/mitmdump.log"; exit 1; }
say "✓ mitmdump listening on 127.0.0.1:$PORT (pid $MITM_PID)"
pause "Ready to run agy?"

# ── 4. Three agy runs ─────────────────────────────────────────────────────
stage "Run agy: two separate processes"
say "Each run is one fresh agy process. Same prompt both times."
for n in 1 2; do
  echo "run$n-fresh-process" > "$LABEL_FILE"
  step "run $n of 2 …"
  agy_through_mitm --print='Reply with exactly SESSION_PROBE_OK' --print-timeout=90s || warn "run $n exited non-zero"
done
say "captured request records so far: $(wc -l < "$OUT" | tr -d ' ')"
pause "Continue to the conversation run?"

stage "Run agy: one conversation, two messages"
echo "run3-one-conversation" > "$LABEL_FILE"
say "Open a SECOND terminal and paste this to start an interactive agy through the proxy:"
printf '\n    HTTPS_PROXY=http://127.0.0.1:%s HTTP_PROXY=http://127.0.0.1:%s SSL_CERT_FILE=%q %q\n\n' \
  "$PORT" "$PORT" "$BUNDLE" "$AGY_BIN"
step "Send the message:  Reply with exactly ONE"
step "Wait for the answer, then send:  Reply with exactly TWO"
step "Exit agy, then come back here."
pause "Done with both messages and agy exited?"
say "captured request records: $(wc -l < "$OUT" | tr -d ' ')"

# ── 5. Summarize ──────────────────────────────────────────────────────────
stage "Summary to paste back"
cleanup; MITM_PID=""
python3 - "$OUT" "$PROBE_DIR/strings-hits.txt" > "$SUMMARY" <<'PY'
import json, sys, collections
rows = [json.loads(l) for l in open(sys.argv[1]) if l.strip()]
print(f"records: {len(rows)}")
table = collections.defaultdict(lambda: collections.defaultdict(set))
for r in rows:
    for h in r.get("body_hits", []):
        table[(r["endpoint"], "body:" + h["path"])][r["label"]].add(h["sha8"])
    for h in r.get("header_hits", []):
        table[(r["endpoint"], "hdr:" + h["name"])][r["label"]].add(h["sha8"])
if not table:
    print("NO session-shaped fields seen (check mitmdump.log; did agy trust the CA?)")
for (endpoint, field), by_label in sorted(table.items()):
    print(f"\n{endpoint}  {field}")
    for label in sorted(by_label):
        print(f"    {label:24s} {sorted(by_label[label])}")
hits = [l.rstrip() for l in open(sys.argv[2])]
print(f"\nstrings hits: {len(hits)} (first 40)")
for l in hits[:40]:
    print("   ", l)
PY
say "Read it: same hash in every run means per-account (or per-machine)."
say "Different between run1 and run2 but constant inside run3 means per-process or per-conversation."
note "Only 8-char hashes and field names are in this file: safe to paste."
printf '\n'; sed 's/^/  /' "$SUMMARY"
printf '\n'
say "Paste everything above back to Claude. Full files: $PROBE_DIR"
# ──────────────────────────────────────────────────────────────────────────

finish
